# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class DraftFormat(StrEnum):
    html = "html"
    markdown = "markdown"
    text = "text"


class PublishPlatform(StrEnum):
    douyin = "douyin"
    wechat = "wechat"
    x = "x"
    zhihu = "zhihu"


class GeneratedByType(StrEnum):
    agent = "agent"
    system = "system"
    user = "user"


class AdaptedAssetType(StrEnum):
    image = "image"


class ProjectStatus(StrEnum):
    draft = "draft"
    ready = "ready"
    publishing = "publishing"
    published = "published"
    failed = "failed"


class PublicationStatus(StrEnum):
    pending = "pending"
    adapted = "adapted"
    publishing = "publishing"
    published = "published"
    failed = "failed"
    disabled = "disabled"


class PublishResultStatus(StrEnum):
    adapted = "adapted"
    error = "error"
    failed = "failed"
    manual_required = "manual_required"
    pending = "pending"
    published = "published"
    publishing = "publishing"


class PlatformAccountStatus(StrEnum):
    unconfigured = "unconfigured"
    untested = "untested"
    connected = "connected"
    failed = "failed"


class ConnectionTestStatus(StrEnum):
    connected = "connected"
    failed = "failed"


class RequirementStatusValue(StrEnum):
    passed = "passed"
    warning = "warning"
    failed = "failed"
    unknown = "unknown"


class BrowserSessionStatus(StrEnum):
    pending = "pending"
    ready = "ready"
    login_detected = "login_detected"
    capturing = "capturing"
    connected = "connected"
    expired = "expired"
    failed = "failed"


class BrowserWorkerSessionStatus(StrEnum):
    ready = "ready"
    login_detected = "login_detected"


class BrowserWorkerCookie(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    value: str
    domain: str
    path: str
    expires: float
    secure: bool
    httpOnly: bool
    sameSite: str


class Match(StrEnum):
    exact = "exact"
    suffix = "suffix"


class BrowserWorkerDomainRule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    host: str
    match: Match
    schemes: list[str]
    purpose: str


class BrowserWorkerCookieRequirement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    domain_suffixes: list[str]
    required: bool
    preserve: bool


class BrowserWorkerViewport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    width: int
    height: int


class BrowserWorkerRemoteAccountProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform_user_id: str
    username: str
    avatar_url: str


class BrowserWorkerStartSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    user_id: UUID
    platform: str
    login_url: str
    allowed_domains: list[BrowserWorkerDomainRule]
    required_cookies: list[BrowserWorkerCookieRequirement]
    initial_cookies: list[BrowserWorkerCookie]
    ttl_seconds: int
    viewport: BrowserWorkerViewport


class BrowserWorkerStartSessionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    worker_session_ref: str
    status: BrowserWorkerSessionStatus
    container_id: str
    cdp_endpoint_ref: str
    stream_endpoint_ref: str
    started_at: AwareDatetime
    expires_at: AwareDatetime


class BrowserWorkerGetSessionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    worker_session_ref: str
    status: BrowserWorkerSessionStatus
    current_url: str
    login_detected: bool
    missing_cookies: list[str]
    message: str


class BrowserWorkerCaptureSessionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: BrowserWorkerSessionStatus
    cookies: list[BrowserWorkerCookie]
    missing_cookies: list[str]
    account: BrowserWorkerRemoteAccountProfile


class BrowserWorkerStartDouyinPublishRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    content: str
    cover_image_base64: str
    cover_image_name: str


class GeneratedBy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: GeneratedByType
    id: constr(min_length=1)
    version: str | None = None
    agent_run_id: str | None = None
    instructions: str | None = None


class AdaptedAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: AdaptedAssetType
    source_url: constr(min_length=1)
    alt: str | None = None


class AdaptedContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: conint(ge=1) | None = None
    format: DraftFormat
    summary: str | None = None
    source_revision: str | None = Field(
        None, description="RFC3339 timestamp or a future revision identifier."
    )
    generated_by: GeneratedBy | None = None
    html: str | None = None
    markdown: str | None = None
    text: str | None = None
    assets: list[AdaptedAsset] | None = None


class DashboardStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total_users: int
    total_projects: int
    total_published_publications: int
    total_failed_publications: int


class PublicationSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    platform: PublishPlatform
    enabled: bool
    status: PublicationStatus
    publish_url: str | None = None


class PublicationDetail(PublicationSummary):
    error_message: str | None = None
    config: dict[str, Any]
    adapted_content: AdaptedContent
    remote_id: str | None = None
    retry_count: int
    last_attempt_at: AwareDatetime | None = None
    published_at: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ProjectPublications(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: UUID
    items: list[PublicationDetail]


class PublishResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: PublishResultStatus
    job_id: UUID | None = None
    platform: PublishPlatform | None = None
    queued_at: AwareDatetime | None = None
    remote_id: str | None = None
    publish_url: str | None = None
    error_message: str | None = None
    browser_session_id: UUID | None = None
    stream_url: str | None = None


class ProjectListItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    user_id: UUID
    title: str
    status: ProjectStatus
    created_at: AwareDatetime
    updated_at: AwareDatetime
    publications: list[PublicationSummary]


class ProjectDetail(ProjectListItem):
    source_content: str


class PaginationProjects(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[ProjectListItem]
    page: int
    limit: int
    total: int
    total_pages: int


class Role(StrEnum):
    user = "user"
    assistant = "assistant"


class AIChatMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Role
    content: str


class AIEditContentRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str | None = None
    content: str
    message: str
    conversation: list[AIChatMessage] | None = None


class Channel(StrEnum):
    content = "content"


class AIEditContentResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    channel: Channel
    content: str


class AIEditPrepublishRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str | None = None
    platform: PublishPlatform
    adapted_content: AdaptedContent
    message: str
    conversation: list[AIChatMessage] | None = None


class Channel1(StrEnum):
    prepublish = "prepublish"


class AIEditPrepublishResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    channel: Channel1
    platform: PublishPlatform
    adapted_content: AdaptedContent
    content: str


class RequirementStatus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: RequirementStatusValue
    title: str
    message: str


class Platform(StrEnum):
    wechat = "wechat"


class WechatAccount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: Platform
    app_id: str
    has_app_secret: bool
    status: PlatformAccountStatus
    last_tested_at: AwareDatetime | None = None
    last_test_error: str | None = None
    updated_at: AwareDatetime | None = None
    ip_whitelist: RequirementStatus
    account_auth: RequirementStatus


class SaveWechatAccountInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    app_id: str
    app_secret: str | None = None


class WechatConnectionTestResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    connected: bool
    status: ConnectionTestStatus
    message: str
    err_code: int | None = None
    err_msg: str | None = None
    tested_at: AwareDatetime
    ip_whitelist: RequirementStatus
    account_auth: RequirementStatus


class Platform1(StrEnum):
    x = "x"


class AuthType(StrEnum):
    oauth1 = "oauth1"
    oauth2 = "oauth2"


class XAccount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: Platform1
    auth_type: AuthType
    api_key: str | None = None
    expires_at: AwareDatetime | None = None
    username: str | None = None
    has_api_secret: bool
    has_access_token: bool
    has_access_token_secret: bool
    has_oauth2_refresh: bool
    status: PlatformAccountStatus
    last_tested_at: AwareDatetime | None = None
    last_test_error: str | None = None
    updated_at: AwareDatetime | None = None
    account_auth: RequirementStatus
    publish_access: RequirementStatus


class SaveXAccountInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    api_key: str | None = None
    api_secret: str | None = None
    access_token: str | None = None
    access_token_secret: str | None = None
    username: str | None = None


class XConnectionTestResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    connected: bool
    status: ConnectionTestStatus
    message: str
    tested_at: AwareDatetime
    user_id: str | None = None
    username: str | None = None
    name: str | None = None
    account_auth: RequirementStatus
    publish_access: RequirementStatus


class Platform2(StrEnum):
    douyin = "douyin"


class DouyinAccount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: Platform2
    username: str | None = None
    avatar_url: str | None = None
    status: PlatformAccountStatus
    last_tested_at: AwareDatetime | None = None
    last_test_error: str | None = None
    updated_at: AwareDatetime | None = None


class Platform3(StrEnum):
    zhihu = "zhihu"


class ZhihuAccount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: Platform3
    username: str | None = None
    avatar_url: str | None = None
    status: PlatformAccountStatus
    last_tested_at: AwareDatetime | None = None
    last_test_error: str | None = None
    updated_at: AwareDatetime | None = None


class BrowserSession(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    platform: PublishPlatform
    status: BrowserSessionStatus
    stream_url: str | None = None
    stream_token_expires_at: AwareDatetime | None = None
    expires_at: AwareDatetime
    message: str | None = None


class StartBrowserSessionResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    status: BrowserSessionStatus
    stream_url: str
    stream_token_expires_at: AwareDatetime
    expires_at: AwareDatetime


class StartPublishBrowserSessionResult(StartBrowserSessionResult):
    platform: PublishPlatform
    project_id: UUID


class Account(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    username: str
    avatar_url: str


class CompleteBrowserSessionResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    platform: PublishPlatform
    status: BrowserSessionStatus
    account: Account
    message: str


class CancelBrowserSessionResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    status: BrowserSessionStatus
