/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    DraftFormat: "html" | "markdown" | "text";
    /** @enum {string} */
    PublishPlatform: "douyin" | "wechat" | "x" | "zhihu";
    /** @enum {string} */
    GeneratedByType: "agent" | "system" | "user";
    /** @enum {string} */
    AdaptedAssetType: "image";
    /** @enum {string} */
    ProjectStatus: "draft" | "ready" | "publishing" | "published" | "failed";
    /** @enum {string} */
    PublicationStatus:
      | "pending"
      | "adapted"
      | "publishing"
      | "published"
      | "failed"
      | "disabled";
    /** @enum {string} */
    PublishResultStatus:
      | "adapted"
      | "error"
      | "failed"
      | "manual_required"
      | "pending"
      | "published"
      | "publishing";
    /** @enum {string} */
    PlatformAccountStatus: "unconfigured" | "untested" | "connected" | "failed";
    /** @enum {string} */
    ConnectionTestStatus: "connected" | "failed";
    /** @enum {string} */
    RequirementStatusValue: "passed" | "warning" | "failed" | "unknown";
    /** @enum {string} */
    BrowserSessionStatus:
      | "pending"
      | "ready"
      | "login_detected"
      | "capturing"
      | "connected"
      | "expired"
      | "failed";
    GeneratedBy: {
      type: components["schemas"]["GeneratedByType"];
      id: string;
      version?: string;
      agent_run_id?: string;
      instructions?: string;
    };
    AdaptedAsset: {
      type: components["schemas"]["AdaptedAssetType"];
      source_url: string;
      alt?: string;
    };
    AdaptedContent: {
      schema_version?: number;
      format: components["schemas"]["DraftFormat"];
      summary?: string;
      /** @description RFC3339 timestamp or a future revision identifier. */
      source_revision?: string;
      generated_by?: components["schemas"]["GeneratedBy"];
      html?: string;
      markdown?: string;
      text?: string;
      assets?: components["schemas"]["AdaptedAsset"][];
    };
    DashboardStats: {
      total_users: number;
      total_projects: number;
      total_published_publications: number;
      total_failed_publications: number;
    };
    PublicationSummary: {
      /** Format: uuid */
      id: string;
      platform: components["schemas"]["PublishPlatform"];
      enabled: boolean;
      status: components["schemas"]["PublicationStatus"];
      publish_url?: string;
    };
    PublicationDetail: components["schemas"]["PublicationSummary"] & {
      error_message?: string;
      config: {
        [key: string]: unknown;
      };
      adapted_content: components["schemas"]["AdaptedContent"];
      remote_id?: string;
      retry_count: number;
      /** Format: date-time */
      last_attempt_at?: string;
      /** Format: date-time */
      published_at?: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    ProjectPublications: {
      /** Format: uuid */
      project_id: string;
      items: components["schemas"]["PublicationDetail"][];
    };
    PublishResult: {
      status: components["schemas"]["PublishResultStatus"];
      /** Format: uuid */
      job_id?: string;
      platform?: components["schemas"]["PublishPlatform"];
      /** Format: date-time */
      queued_at?: string;
      remote_id?: string;
      publish_url?: string;
      error_message?: string;
      /** Format: uuid */
      browser_session_id?: string;
      stream_url?: string;
    };
    ProjectListItem: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      user_id: string;
      title: string;
      status: components["schemas"]["ProjectStatus"];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      publications: components["schemas"]["PublicationSummary"][];
    };
    ProjectDetail: components["schemas"]["ProjectListItem"] & {
      source_content: string;
    };
    PaginationProjects: {
      items: components["schemas"]["ProjectListItem"][];
      page: number;
      limit: number;
      total: number;
      total_pages: number;
    };
    AIChatMessage: {
      /** @enum {string} */
      role: "user" | "assistant";
      content: string;
    };
    AIEditContentRequest: {
      title?: string;
      content: string;
      message: string;
      conversation?: components["schemas"]["AIChatMessage"][];
    };
    AIEditContentResponse: {
      /** @enum {string} */
      channel: "content";
      content: string;
    };
    AIEditPrepublishRequest: {
      title?: string;
      platform: components["schemas"]["PublishPlatform"];
      adapted_content: components["schemas"]["AdaptedContent"];
      message: string;
      conversation?: components["schemas"]["AIChatMessage"][];
    };
    AIEditPrepublishResponse: {
      /** @enum {string} */
      channel: "prepublish";
      platform: components["schemas"]["PublishPlatform"];
      adapted_content: components["schemas"]["AdaptedContent"];
      content: string;
    };
    RequirementStatus: {
      status: components["schemas"]["RequirementStatusValue"];
      title: string;
      message: string;
    };
    WechatAccount: {
      /** @enum {string} */
      platform: "wechat";
      app_id: string;
      has_app_secret: boolean;
      status: components["schemas"]["PlatformAccountStatus"];
      /** Format: date-time */
      last_tested_at?: string;
      last_test_error?: string;
      /** Format: date-time */
      updated_at?: string;
      ip_whitelist: components["schemas"]["RequirementStatus"];
      account_auth: components["schemas"]["RequirementStatus"];
    };
    SaveWechatAccountInput: {
      app_id: string;
      app_secret?: string;
    };
    WechatConnectionTestResult: {
      connected: boolean;
      status: components["schemas"]["ConnectionTestStatus"];
      message: string;
      err_code?: number;
      err_msg?: string;
      /** Format: date-time */
      tested_at: string;
      ip_whitelist: components["schemas"]["RequirementStatus"];
      account_auth: components["schemas"]["RequirementStatus"];
    };
    XAccount: {
      /** @enum {string} */
      platform: "x";
      /** @enum {string} */
      auth_type: "oauth1" | "oauth2";
      api_key?: string;
      /** Format: date-time */
      expires_at?: string;
      username?: string;
      has_api_secret: boolean;
      has_access_token: boolean;
      has_access_token_secret: boolean;
      has_oauth2_refresh: boolean;
      status: components["schemas"]["PlatformAccountStatus"];
      /** Format: date-time */
      last_tested_at?: string;
      last_test_error?: string;
      /** Format: date-time */
      updated_at?: string;
      account_auth: components["schemas"]["RequirementStatus"];
      publish_access: components["schemas"]["RequirementStatus"];
    };
    SaveXAccountInput: {
      api_key?: string;
      api_secret?: string;
      access_token?: string;
      access_token_secret?: string;
      username?: string;
    };
    XConnectionTestResult: {
      connected: boolean;
      status: components["schemas"]["ConnectionTestStatus"];
      message: string;
      /** Format: date-time */
      tested_at: string;
      user_id?: string;
      username?: string;
      name?: string;
      account_auth: components["schemas"]["RequirementStatus"];
      publish_access: components["schemas"]["RequirementStatus"];
    };
    DouyinAccount: {
      /** @enum {string} */
      platform: "douyin";
      username?: string;
      avatar_url?: string;
      status: components["schemas"]["PlatformAccountStatus"];
      /** Format: date-time */
      last_tested_at?: string;
      last_test_error?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    ZhihuAccount: {
      /** @enum {string} */
      platform: "zhihu";
      username?: string;
      avatar_url?: string;
      status: components["schemas"]["PlatformAccountStatus"];
      /** Format: date-time */
      last_tested_at?: string;
      last_test_error?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    BrowserSession: {
      /** Format: uuid */
      session_id: string;
      platform: components["schemas"]["PublishPlatform"];
      status: components["schemas"]["BrowserSessionStatus"];
      stream_url?: string;
      /** Format: date-time */
      stream_token_expires_at?: string;
      /** Format: date-time */
      expires_at: string;
      message?: string;
    };
    StartBrowserSessionResult: {
      /** Format: uuid */
      session_id: string;
      status: components["schemas"]["BrowserSessionStatus"];
      stream_url: string;
      /** Format: date-time */
      stream_token_expires_at: string;
      /** Format: date-time */
      expires_at: string;
    };
    StartPublishBrowserSessionResult: components["schemas"]["StartBrowserSessionResult"] & {
      platform: components["schemas"]["PublishPlatform"];
      /** Format: uuid */
      project_id: string;
    };
    CompleteBrowserSessionResult: {
      /** Format: uuid */
      session_id: string;
      platform: components["schemas"]["PublishPlatform"];
      status: components["schemas"]["BrowserSessionStatus"];
      account: {
        username: string;
        avatar_url: string;
      };
      message: string;
    };
    CancelBrowserSessionResult: {
      /** Format: uuid */
      session_id: string;
      status: components["schemas"]["BrowserSessionStatus"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
