// Package contracts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package contracts

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AIChatMessageRole.
const (
	AIChatMessageRoleAssistant AIChatMessageRole = "assistant"
	AIChatMessageRoleUser      AIChatMessageRole = "user"
)

// Defines values for AIEditContentResponseChannel.
const (
	Content AIEditContentResponseChannel = "content"
)

// Defines values for AIEditPrepublishResponseChannel.
const (
	Prepublish AIEditPrepublishResponseChannel = "prepublish"
)

// Defines values for AdaptedAssetType.
const (
	Image AdaptedAssetType = "image"
)

// Defines values for BrowserSessionStatus.
const (
	BrowserSessionStatusCapturing     BrowserSessionStatus = "capturing"
	BrowserSessionStatusConnected     BrowserSessionStatus = "connected"
	BrowserSessionStatusExpired       BrowserSessionStatus = "expired"
	BrowserSessionStatusFailed        BrowserSessionStatus = "failed"
	BrowserSessionStatusLoginDetected BrowserSessionStatus = "login_detected"
	BrowserSessionStatusPending       BrowserSessionStatus = "pending"
	BrowserSessionStatusReady         BrowserSessionStatus = "ready"
)

// Defines values for BrowserWorkerDomainRuleMatch.
const (
	Exact  BrowserWorkerDomainRuleMatch = "exact"
	Suffix BrowserWorkerDomainRuleMatch = "suffix"
)

// Defines values for BrowserWorkerSessionStatus.
const (
	BrowserWorkerSessionStatusLoginDetected BrowserWorkerSessionStatus = "login_detected"
	BrowserWorkerSessionStatusReady         BrowserWorkerSessionStatus = "ready"
)

// Defines values for ConnectionTestStatus.
const (
	ConnectionTestStatusConnected ConnectionTestStatus = "connected"
	ConnectionTestStatusFailed    ConnectionTestStatus = "failed"
)

// Defines values for DouyinAccountPlatform.
const (
	DouyinAccountPlatformDouyin DouyinAccountPlatform = "douyin"
)

// Defines values for DraftFormat.
const (
	Html     DraftFormat = "html"
	Markdown DraftFormat = "markdown"
	Text     DraftFormat = "text"
)

// Defines values for GeneratedByType.
const (
	GeneratedByTypeAgent  GeneratedByType = "agent"
	GeneratedByTypeSystem GeneratedByType = "system"
	GeneratedByTypeUser   GeneratedByType = "user"
)

// Defines values for PlatformAccountStatus.
const (
	PlatformAccountStatusConnected    PlatformAccountStatus = "connected"
	PlatformAccountStatusFailed       PlatformAccountStatus = "failed"
	PlatformAccountStatusUnconfigured PlatformAccountStatus = "unconfigured"
	PlatformAccountStatusUntested     PlatformAccountStatus = "untested"
)

// Defines values for ProjectStatus.
const (
	ProjectStatusDraft      ProjectStatus = "draft"
	ProjectStatusFailed     ProjectStatus = "failed"
	ProjectStatusPublished  ProjectStatus = "published"
	ProjectStatusPublishing ProjectStatus = "publishing"
	ProjectStatusReady      ProjectStatus = "ready"
)

// Defines values for PublicationStatus.
const (
	PublicationStatusAdapted    PublicationStatus = "adapted"
	PublicationStatusDisabled   PublicationStatus = "disabled"
	PublicationStatusFailed     PublicationStatus = "failed"
	PublicationStatusPending    PublicationStatus = "pending"
	PublicationStatusPublished  PublicationStatus = "published"
	PublicationStatusPublishing PublicationStatus = "publishing"
)

// Defines values for PublishPlatform.
const (
	PublishPlatformDouyin PublishPlatform = "douyin"
	PublishPlatformWechat PublishPlatform = "wechat"
	PublishPlatformX      PublishPlatform = "x"
	PublishPlatformZhihu  PublishPlatform = "zhihu"
)

// Defines values for PublishResultStatus.
const (
	PublishResultStatusAdapted        PublishResultStatus = "adapted"
	PublishResultStatusError          PublishResultStatus = "error"
	PublishResultStatusFailed         PublishResultStatus = "failed"
	PublishResultStatusManualRequired PublishResultStatus = "manual_required"
	PublishResultStatusPending        PublishResultStatus = "pending"
	PublishResultStatusPublished      PublishResultStatus = "published"
	PublishResultStatusPublishing     PublishResultStatus = "publishing"
)

// Defines values for RequirementStatusValue.
const (
	RequirementStatusValueFailed  RequirementStatusValue = "failed"
	RequirementStatusValuePassed  RequirementStatusValue = "passed"
	RequirementStatusValueUnknown RequirementStatusValue = "unknown"
	RequirementStatusValueWarning RequirementStatusValue = "warning"
)

// Defines values for WechatAccountPlatform.
const (
	Wechat WechatAccountPlatform = "wechat"
)

// Defines values for XAccountAuthType.
const (
	Oauth1 XAccountAuthType = "oauth1"
	Oauth2 XAccountAuthType = "oauth2"
)

// Defines values for XAccountPlatform.
const (
	X XAccountPlatform = "x"
)

// Defines values for ZhihuAccountPlatform.
const (
	Zhihu ZhihuAccountPlatform = "zhihu"
)

// AIChatMessage defines model for AIChatMessage.
type AIChatMessage struct {
	Content string            `json:"content"`
	Role    AIChatMessageRole `json:"role"`
}

// AIChatMessageRole defines model for AIChatMessage.Role.
type AIChatMessageRole string

// AIEditContentRequest defines model for AIEditContentRequest.
type AIEditContentRequest struct {
	Content      string           `json:"content"`
	Conversation *[]AIChatMessage `json:"conversation,omitempty"`
	Message      string           `json:"message"`
	Title        *string          `json:"title,omitempty"`
}

// AIEditContentResponse defines model for AIEditContentResponse.
type AIEditContentResponse struct {
	Channel AIEditContentResponseChannel `json:"channel"`
	Content string                       `json:"content"`
}

// AIEditContentResponseChannel defines model for AIEditContentResponse.Channel.
type AIEditContentResponseChannel string

// AIEditPrepublishRequest defines model for AIEditPrepublishRequest.
type AIEditPrepublishRequest struct {
	AdaptedContent AdaptedContent   `json:"adapted_content"`
	Conversation   *[]AIChatMessage `json:"conversation,omitempty"`
	Message        string           `json:"message"`
	Platform       PublishPlatform  `json:"platform"`
	Title          *string          `json:"title,omitempty"`
}

// AIEditPrepublishResponse defines model for AIEditPrepublishResponse.
type AIEditPrepublishResponse struct {
	AdaptedContent AdaptedContent                  `json:"adapted_content"`
	Channel        AIEditPrepublishResponseChannel `json:"channel"`
	Content        string                          `json:"content"`
	Platform       PublishPlatform                 `json:"platform"`
}

// AIEditPrepublishResponseChannel defines model for AIEditPrepublishResponse.Channel.
type AIEditPrepublishResponseChannel string

// AdaptedAsset defines model for AdaptedAsset.
type AdaptedAsset struct {
	Alt       *string          `json:"alt,omitempty"`
	SourceUrl string           `json:"source_url"`
	Type      AdaptedAssetType `json:"type"`
}

// AdaptedAssetType defines model for AdaptedAssetType.
type AdaptedAssetType string

// AdaptedContent defines model for AdaptedContent.
type AdaptedContent struct {
	Assets        *[]AdaptedAsset `json:"assets,omitempty"`
	Format        DraftFormat     `json:"format"`
	GeneratedBy   *GeneratedBy    `json:"generated_by,omitempty"`
	Html          *string         `json:"html,omitempty"`
	Markdown      *string         `json:"markdown,omitempty"`
	SchemaVersion *int            `json:"schema_version,omitempty"`

	// SourceRevision RFC3339 timestamp or a future revision identifier.
	SourceRevision *string `json:"source_revision,omitempty"`
	Summary        *string `json:"summary,omitempty"`
	Text           *string `json:"text,omitempty"`
}

// BrowserSession defines model for BrowserSession.
type BrowserSession struct {
	ExpiresAt            time.Time            `json:"expires_at"`
	Message              *string              `json:"message,omitempty"`
	Platform             PublishPlatform      `json:"platform"`
	SessionId            openapi_types.UUID   `json:"session_id"`
	Status               BrowserSessionStatus `json:"status"`
	StreamTokenExpiresAt *time.Time           `json:"stream_token_expires_at,omitempty"`
	StreamUrl            *string              `json:"stream_url,omitempty"`
}

// BrowserSessionStatus defines model for BrowserSessionStatus.
type BrowserSessionStatus string

// BrowserWorkerCaptureSessionResponse defines model for BrowserWorkerCaptureSessionResponse.
type BrowserWorkerCaptureSessionResponse struct {
	Account        BrowserWorkerRemoteAccountProfile `json:"account"`
	Cookies        []BrowserWorkerCookie             `json:"cookies"`
	MissingCookies []string                          `json:"missing_cookies"`
	Status         BrowserWorkerSessionStatus        `json:"status"`
}

// BrowserWorkerCookie defines model for BrowserWorkerCookie.
type BrowserWorkerCookie struct {
	Domain   string  `json:"domain"`
	Expires  float64 `json:"expires"`
	HttpOnly bool    `json:"httpOnly"`
	Name     string  `json:"name"`
	Path     string  `json:"path"`
	SameSite string  `json:"sameSite"`
	Secure   bool    `json:"secure"`
	Value    string  `json:"value"`
}

// BrowserWorkerCookieRequirement defines model for BrowserWorkerCookieRequirement.
type BrowserWorkerCookieRequirement struct {
	DomainSuffixes []string `json:"domain_suffixes"`
	Name           string   `json:"name"`
	Preserve       bool     `json:"preserve"`
	Required       bool     `json:"required"`
}

// BrowserWorkerDomainRule defines model for BrowserWorkerDomainRule.
type BrowserWorkerDomainRule struct {
	Host    string                       `json:"host"`
	Match   BrowserWorkerDomainRuleMatch `json:"match"`
	Purpose string                       `json:"purpose"`
	Schemes []string                     `json:"schemes"`
}

// BrowserWorkerDomainRuleMatch defines model for BrowserWorkerDomainRule.Match.
type BrowserWorkerDomainRuleMatch string

// BrowserWorkerGetSessionResponse defines model for BrowserWorkerGetSessionResponse.
type BrowserWorkerGetSessionResponse struct {
	CurrentURL       string                     `json:"current_url"`
	LoginDetected    bool                       `json:"login_detected"`
	Message          string                     `json:"message"`
	MissingCookies   []string                   `json:"missing_cookies"`
	Status           BrowserWorkerSessionStatus `json:"status"`
	WorkerSessionRef string                     `json:"worker_session_ref"`
}

// BrowserWorkerRemoteAccountProfile defines model for BrowserWorkerRemoteAccountProfile.
type BrowserWorkerRemoteAccountProfile struct {
	AvatarURL      string `json:"avatar_url"`
	PlatformUserID string `json:"platform_user_id"`
	Username       string `json:"username"`
}

// BrowserWorkerSessionStatus defines model for BrowserWorkerSessionStatus.
type BrowserWorkerSessionStatus string

// BrowserWorkerStartDouyinPublishRequest defines model for BrowserWorkerStartDouyinPublishRequest.
type BrowserWorkerStartDouyinPublishRequest struct {
	Content          string `json:"content"`
	CoverImageBase64 string `json:"cover_image_base64"`
	CoverImageName   string `json:"cover_image_name"`
	Title            string `json:"title"`
}

// BrowserWorkerStartSessionRequest defines model for BrowserWorkerStartSessionRequest.
type BrowserWorkerStartSessionRequest struct {
	AllowedDomains  []BrowserWorkerDomainRule        `json:"allowed_domains"`
	InitialCookies  []BrowserWorkerCookie            `json:"initial_cookies"`
	LoginURL        string                           `json:"login_url"`
	Platform        string                           `json:"platform"`
	RequiredCookies []BrowserWorkerCookieRequirement `json:"required_cookies"`
	SessionID       openapi_types.UUID               `json:"session_id"`
	TTLSeconds      int                              `json:"ttl_seconds"`
	UserID          openapi_types.UUID               `json:"user_id"`
	Viewport        BrowserWorkerViewport            `json:"viewport"`
}

// BrowserWorkerStartSessionResponse defines model for BrowserWorkerStartSessionResponse.
type BrowserWorkerStartSessionResponse struct {
	CDPEndpointRef    string                     `json:"cdp_endpoint_ref"`
	ContainerID       string                     `json:"container_id"`
	ExpiresAt         time.Time                  `json:"expires_at"`
	StartedAt         time.Time                  `json:"started_at"`
	Status            BrowserWorkerSessionStatus `json:"status"`
	StreamEndpointRef string                     `json:"stream_endpoint_ref"`
	WorkerSessionRef  string                     `json:"worker_session_ref"`
}

// BrowserWorkerViewport defines model for BrowserWorkerViewport.
type BrowserWorkerViewport struct {
	Height int `json:"height"`
	Width  int `json:"width"`
}

// CancelBrowserSessionResult defines model for CancelBrowserSessionResult.
type CancelBrowserSessionResult struct {
	SessionId openapi_types.UUID   `json:"session_id"`
	Status    BrowserSessionStatus `json:"status"`
}

// CompleteBrowserSessionResult defines model for CompleteBrowserSessionResult.
type CompleteBrowserSessionResult struct {
	Account struct {
		AvatarUrl string `json:"avatar_url"`
		Username  string `json:"username"`
	} `json:"account"`
	Message   string               `json:"message"`
	Platform  PublishPlatform      `json:"platform"`
	SessionId openapi_types.UUID   `json:"session_id"`
	Status    BrowserSessionStatus `json:"status"`
}

// ConnectionTestStatus defines model for ConnectionTestStatus.
type ConnectionTestStatus string

// DashboardStats defines model for DashboardStats.
type DashboardStats struct {
	TotalFailedPublications    int `json:"total_failed_publications"`
	TotalProjects              int `json:"total_projects"`
	TotalPublishedPublications int `json:"total_published_publications"`
	TotalUsers                 int `json:"total_users"`
}

// DouyinAccount defines model for DouyinAccount.
type DouyinAccount struct {
	AvatarUrl     *string               `json:"avatar_url,omitempty"`
	LastTestError *string               `json:"last_test_error,omitempty"`
	LastTestedAt  *time.Time            `json:"last_tested_at,omitempty"`
	Platform      DouyinAccountPlatform `json:"platform"`
	Status        PlatformAccountStatus `json:"status"`
	UpdatedAt     *time.Time            `json:"updated_at,omitempty"`
	Username      *string               `json:"username,omitempty"`
}

// DouyinAccountPlatform defines model for DouyinAccount.Platform.
type DouyinAccountPlatform string

// DraftFormat defines model for DraftFormat.
type DraftFormat string

// GeneratedBy defines model for GeneratedBy.
type GeneratedBy struct {
	AgentRunId   *string         `json:"agent_run_id,omitempty"`
	Id           string          `json:"id"`
	Instructions *string         `json:"instructions,omitempty"`
	Type         GeneratedByType `json:"type"`
	Version      *string         `json:"version,omitempty"`
}

// GeneratedByType defines model for GeneratedByType.
type GeneratedByType string

// PaginationProjects defines model for PaginationProjects.
type PaginationProjects struct {
	Items      []ProjectListItem `json:"items"`
	Limit      int               `json:"limit"`
	Page       int               `json:"page"`
	Total      int               `json:"total"`
	TotalPages int               `json:"total_pages"`
}

// PlatformAccountStatus defines model for PlatformAccountStatus.
type PlatformAccountStatus string

// ProjectDetail defines model for ProjectDetail.
type ProjectDetail struct {
	CreatedAt     time.Time            `json:"created_at"`
	Id            openapi_types.UUID   `json:"id"`
	Publications  []PublicationSummary `json:"publications"`
	SourceContent string               `json:"source_content"`
	Status        ProjectStatus        `json:"status"`
	Title         string               `json:"title"`
	UpdatedAt     time.Time            `json:"updated_at"`
	UserId        openapi_types.UUID   `json:"user_id"`
}

// ProjectListItem defines model for ProjectListItem.
type ProjectListItem struct {
	CreatedAt    time.Time            `json:"created_at"`
	Id           openapi_types.UUID   `json:"id"`
	Publications []PublicationSummary `json:"publications"`
	Status       ProjectStatus        `json:"status"`
	Title        string               `json:"title"`
	UpdatedAt    time.Time            `json:"updated_at"`
	UserId       openapi_types.UUID   `json:"user_id"`
}

// ProjectPublications defines model for ProjectPublications.
type ProjectPublications struct {
	Items     []PublicationDetail `json:"items"`
	ProjectId openapi_types.UUID  `json:"project_id"`
}

// ProjectStatus defines model for ProjectStatus.
type ProjectStatus string

// PublicationDetail defines model for PublicationDetail.
type PublicationDetail struct {
	AdaptedContent AdaptedContent         `json:"adapted_content"`
	Config         map[string]interface{} `json:"config"`
	CreatedAt      time.Time              `json:"created_at"`
	Enabled        bool                   `json:"enabled"`
	ErrorMessage   *string                `json:"error_message,omitempty"`
	Id             openapi_types.UUID     `json:"id"`
	LastAttemptAt  *time.Time             `json:"last_attempt_at,omitempty"`
	Platform       PublishPlatform        `json:"platform"`
	PublishUrl     *string                `json:"publish_url,omitempty"`
	PublishedAt    *time.Time             `json:"published_at,omitempty"`
	RemoteId       *string                `json:"remote_id,omitempty"`
	RetryCount     int                    `json:"retry_count"`
	Status         PublicationStatus      `json:"status"`
	UpdatedAt      time.Time              `json:"updated_at"`
}

// PublicationStatus defines model for PublicationStatus.
type PublicationStatus string

// PublicationSummary defines model for PublicationSummary.
type PublicationSummary struct {
	Enabled    bool               `json:"enabled"`
	Id         openapi_types.UUID `json:"id"`
	Platform   PublishPlatform    `json:"platform"`
	PublishUrl *string            `json:"publish_url,omitempty"`
	Status     PublicationStatus  `json:"status"`
}

// PublishPlatform defines model for PublishPlatform.
type PublishPlatform string

// PublishResult defines model for PublishResult.
type PublishResult struct {
	BrowserSessionId *openapi_types.UUID `json:"browser_session_id,omitempty"`
	ErrorMessage     *string             `json:"error_message,omitempty"`
	JobId            *openapi_types.UUID `json:"job_id,omitempty"`
	Platform         *PublishPlatform    `json:"platform,omitempty"`
	PublishUrl       *string             `json:"publish_url,omitempty"`
	QueuedAt         *time.Time          `json:"queued_at,omitempty"`
	RemoteId         *string             `json:"remote_id,omitempty"`
	Status           PublishResultStatus `json:"status"`
	StreamUrl        *string             `json:"stream_url,omitempty"`
}

// PublishResultStatus defines model for PublishResultStatus.
type PublishResultStatus string

// RequirementStatus defines model for RequirementStatus.
type RequirementStatus struct {
	Message string                 `json:"message"`
	Status  RequirementStatusValue `json:"status"`
	Title   string                 `json:"title"`
}

// RequirementStatusValue defines model for RequirementStatusValue.
type RequirementStatusValue string

// SaveWechatAccountInput defines model for SaveWechatAccountInput.
type SaveWechatAccountInput struct {
	AppId     string  `json:"app_id"`
	AppSecret *string `json:"app_secret,omitempty"`
}

// SaveXAccountInput defines model for SaveXAccountInput.
type SaveXAccountInput struct {
	AccessToken       *string `json:"access_token,omitempty"`
	AccessTokenSecret *string `json:"access_token_secret,omitempty"`
	ApiKey            *string `json:"api_key,omitempty"`
	ApiSecret         *string `json:"api_secret,omitempty"`
	Username          *string `json:"username,omitempty"`
}

// StartBrowserSessionResult defines model for StartBrowserSessionResult.
type StartBrowserSessionResult struct {
	ExpiresAt            time.Time            `json:"expires_at"`
	SessionId            openapi_types.UUID   `json:"session_id"`
	Status               BrowserSessionStatus `json:"status"`
	StreamTokenExpiresAt time.Time            `json:"stream_token_expires_at"`
	StreamUrl            string               `json:"stream_url"`
}

// StartPublishBrowserSessionResult defines model for StartPublishBrowserSessionResult.
type StartPublishBrowserSessionResult struct {
	ExpiresAt            time.Time            `json:"expires_at"`
	Platform             PublishPlatform      `json:"platform"`
	ProjectId            openapi_types.UUID   `json:"project_id"`
	SessionId            openapi_types.UUID   `json:"session_id"`
	Status               BrowserSessionStatus `json:"status"`
	StreamTokenExpiresAt time.Time            `json:"stream_token_expires_at"`
	StreamUrl            string               `json:"stream_url"`
}

// WechatAccount defines model for WechatAccount.
type WechatAccount struct {
	AccountAuth   RequirementStatus     `json:"account_auth"`
	AppId         string                `json:"app_id"`
	HasAppSecret  bool                  `json:"has_app_secret"`
	IpWhitelist   RequirementStatus     `json:"ip_whitelist"`
	LastTestError *string               `json:"last_test_error,omitempty"`
	LastTestedAt  *time.Time            `json:"last_tested_at,omitempty"`
	Platform      WechatAccountPlatform `json:"platform"`
	Status        PlatformAccountStatus `json:"status"`
	UpdatedAt     *time.Time            `json:"updated_at,omitempty"`
}

// WechatAccountPlatform defines model for WechatAccount.Platform.
type WechatAccountPlatform string

// WechatConnectionTestResult defines model for WechatConnectionTestResult.
type WechatConnectionTestResult struct {
	AccountAuth RequirementStatus    `json:"account_auth"`
	Connected   bool                 `json:"connected"`
	ErrCode     *int                 `json:"err_code,omitempty"`
	ErrMsg      *string              `json:"err_msg,omitempty"`
	IpWhitelist RequirementStatus    `json:"ip_whitelist"`
	Message     string               `json:"message"`
	Status      ConnectionTestStatus `json:"status"`
	TestedAt    time.Time            `json:"tested_at"`
}

// XAccount defines model for XAccount.
type XAccount struct {
	AccountAuth          RequirementStatus     `json:"account_auth"`
	ApiKey               *string               `json:"api_key,omitempty"`
	AuthType             XAccountAuthType      `json:"auth_type"`
	ExpiresAt            *time.Time            `json:"expires_at,omitempty"`
	HasAccessToken       bool                  `json:"has_access_token"`
	HasAccessTokenSecret bool                  `json:"has_access_token_secret"`
	HasApiSecret         bool                  `json:"has_api_secret"`
	HasOauth2Refresh     bool                  `json:"has_oauth2_refresh"`
	LastTestError        *string               `json:"last_test_error,omitempty"`
	LastTestedAt         *time.Time            `json:"last_tested_at,omitempty"`
	Platform             XAccountPlatform      `json:"platform"`
	PublishAccess        RequirementStatus     `json:"publish_access"`
	Status               PlatformAccountStatus `json:"status"`
	UpdatedAt            *time.Time            `json:"updated_at,omitempty"`
	Username             *string               `json:"username,omitempty"`
}

// XAccountAuthType defines model for XAccount.AuthType.
type XAccountAuthType string

// XAccountPlatform defines model for XAccount.Platform.
type XAccountPlatform string

// XConnectionTestResult defines model for XConnectionTestResult.
type XConnectionTestResult struct {
	AccountAuth   RequirementStatus    `json:"account_auth"`
	Connected     bool                 `json:"connected"`
	Message       string               `json:"message"`
	Name          *string              `json:"name,omitempty"`
	PublishAccess RequirementStatus    `json:"publish_access"`
	Status        ConnectionTestStatus `json:"status"`
	TestedAt      time.Time            `json:"tested_at"`
	UserId        *string              `json:"user_id,omitempty"`
	Username      *string              `json:"username,omitempty"`
}

// ZhihuAccount defines model for ZhihuAccount.
type ZhihuAccount struct {
	AvatarUrl     *string               `json:"avatar_url,omitempty"`
	LastTestError *string               `json:"last_test_error,omitempty"`
	LastTestedAt  *time.Time            `json:"last_tested_at,omitempty"`
	Platform      ZhihuAccountPlatform  `json:"platform"`
	Status        PlatformAccountStatus `json:"status"`
	UpdatedAt     *time.Time            `json:"updated_at,omitempty"`
	Username      *string               `json:"username,omitempty"`
}

// ZhihuAccountPlatform defines model for ZhihuAccount.Platform.
type ZhihuAccountPlatform string

// CreateBrowserWorkerSessionJSONRequestBody defines body for CreateBrowserWorkerSession for application/json ContentType.
type CreateBrowserWorkerSessionJSONRequestBody = BrowserWorkerStartSessionRequest

// StartBrowserWorkerDouyinPublishJSONRequestBody defines body for StartBrowserWorkerDouyinPublish for application/json ContentType.
type StartBrowserWorkerDouyinPublishJSONRequestBody = BrowserWorkerStartDouyinPublishRequest
